---
title: "2024_06_Chlorophyll_Abundance"
author: "Cindy Fajardo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "../Output/")
```

#Libraries
```{r, Libraries}
library("rerddap")
library(tidyverse)
library("tidync")
library("doParallel")
library(lubridate)
library(patchwork)
library(viridis)
library(here)
library(kableExtra)
library(hrbrthemes)
library(emmeans)
library(agricolae)
library(vegan)
library(performance)
library(broom)
library(car)
library(lme4)
library(lmerTest)
library(pscl)
library(ggridges)
library(devtools)
library(pairwiseAdonis)
library(gcookbook)
library(ggsci)
library(Hmisc)
```

#Read in CSV
```{r, Read in CSV}
orig_spec_chl_abun <- read_csv(here("Data","Chlorophyll_absorbance_data_sheet_orig.csv"))

```

#Spectophotometry Data Manipulation
```{r, Spectophotometry Data Manipulation}
chl_abun <- orig_spec_chl_abun %>%
  separate(col = Plate_ID,
           into = c("Plate", "ID"),
           sep = "_") %>%
  mutate(Path_length_cm = Path_lenght_mm/10) %>% 
  mutate(ug_ml = ((Abun_665-Abun_750)/Path_length_cm),
         ug = ug_ml *Metha_vol,
         ug_cm2 = ug/SA_cm_2) %>% 
  group_by(Plate, Group) %>% 
  summarise(mean_ug_cm2 = mean(ug_cm2 ),
            se_ug_cm2 = sd(ug_cm2)/sqrt(n())) %>% 
  mutate(Group = as.factor(Group))%>% 
  mutate(Plate_Type = case_when(
    Plate %in% c("C1","C2","C3","C4") ~ "Control",
    Plate %in% c("F1","F2","F3","F4","F6","F7","F8","F10","F5") ~ "Female",
    Plate %in% c("M1","M2","M3","M4","M5","M6","M8","M9","M10") ~ "Male",
    Plate %in% ("UK") ~ "Unknown"))
  
```


#Chl Concentration Boxplot
```{r, Chl Concentration Boxplot}
chl_conc_boxplot <-chl_abun %>% 
  filter(Plate_Type != "Unknown") %>% 
  ggplot(aes(x=Plate_Type,
         y = mean_ug_cm2,
         fill = Plate_Type))+
  geom_boxplot(show.legend = FALSE)+
  labs(title = "Chlorophyll Concentration",
       fill = "Plate_Type",
       x = "Cage Type",
       y = "Chlorophyll Concentration μg/cm²")+
  scale_fill_bmj()+
  theme_bw()
  
chl_conc_boxplot


```

#Only Females and Males
```{r, Only Females and Males}
orig_only_fem_male <- orig_spec_chl_abun %>%
  separate(col = Plate_ID,
           into = c("Plate", "ID"),
           sep = "_") %>%
  mutate(Path_length_cm = Path_lenght_mm/10) %>% 
  mutate(ug_ml = ((Abun_665-Abun_750)/Path_length_cm),
         ug = ug_ml *Metha_vol,
         ug_cm2 = ug/SA_cm_2) %>% 
  group_by(Plate, Group) %>% 
  summarise(mean_ug_cm2 = mean(ug_cm2 ),
            se_ug_cm2 = sd(ug_cm2)/sqrt(n())) %>% 
  mutate(Group = as.factor(Group)) %>% 
  mutate(Plate_Type = case_when(
    Plate %in% c("C1","C2","C3","C4") ~ "Control",
    Plate %in% c("F1","F2","F3","F4","F6","F7","F8","F10","F5") ~ "Female",
    Plate %in% c("M1","M2","M3","M4","M5","M6","M8","M9","M10") ~ "Male",
    Plate %in% ("UK") ~ "Unknown")) %>% 
  filter(Plate_Type != "Control") %>% 
  filter(Plate_Type != "Unknown") %>% 
  mutate(Group = case_when(
    Plate %in% c("F1", "M1") ~ "1",
    Plate %in% c("F2", "M2") ~ "2",
    Plate %in% c("F3", "M3") ~ "3",
    Plate %in% c ("F4", "M4") ~ "4",
    Plate %in% c("F5", "M5") ~ "5",
    Plate %in% c("F6", "M6") ~ "6",
    Plate %in% c("F7") ~"7",
    Plate %in% c("F8", "M8") ~"8",
    Plate %in% c("M9") ~ "9",
    Plate %in% c("F10", "M10") ~"10"))
```

#Paired Graph
```{r, Paired Graph}
orig_paired_graph <- orig_only_fem_male %>% 
  ggplot(aes(x = Plate_Type, 
             y = mean_ug_cm2)) +
  stat_summary(aes(group = Group), 
               fun = mean, 
               geom = "path",
               show.legend = FALSE) +
  stat_summary(aes(color = Plate), 
               fun.data = mean_cl_boot,
               show.legend = FALSE) +
  stat_summary(aes(color = Group), 
               fun = mean, 
               geom = "point", 
               size = 4,
               show.legend = FALSE) +
  geom_point(aes(color = Group),
             show.legend = FALSE)+
  labs(title = "Chlorophyll Concentartion of Paired Female and Male Cages",
       x = "Cage Type",
       y = "Chlorophyll Concentration μg/mm²")+
  theme_bw()

orig_paired_graph

```

#General Linear Models
```{r, General Linear Models}
Mod_chl<-lmer(mean_ug_cm2~Plate_Type+(1|Group), data = orig_only_fem_male %>%
                filter(Plate_Type %in% c("Male","Female")) ) # you are getting the singularity warning because you have two points without a pair
anova(Mod_chl)
summary(Mod_chl)
```

